name: 'bloaty-analyze'
author: Damian Jarek
description: 'Run Bloaty McBloatface on your binaries'

inputs:
    demangle-mode:
        description: 'Demangle mode.'
        default: 'short'
    domain:
        description: 'Controls the domains shown.'
        default: 'both'
    rows:
        description: 'Number of rows shown. Set to 0 for unlimited.'
        default: '20'
    sources:
        description: 'Comma separated list of sources.'
        default: 'symbols'
    file:
        description: 'File to be analyzed.'
        required: true
    resultsfile:
        description: 'Name of file to write the results to'
        default: 'bloaty.out'
    base-file:
        description: 'Base file used for diffs. Shows absolute sizes if not set.'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - bloaty -d ${{ inputs.sources }} --demangle=${{ inputs.demangle-mode }} --domain=${{ inputs.domain }} -n ${{ inputs.rows }} ${{ inputs.file }} -- ${{ inputs.base-file }} 2>&1 |tee ${{ inputs.resultsfile }} ;

branding:
    icon: 'bar-chart'
    color: 'gray-dark'
